### ISSUE TITLE
Parse and format JSON from the SF 311 API

### ISSUE THREAD

**Issue by masparasol** [SFcityMeters/SFcityMeters#5]
The index.html file contains a vanilla JS AJAX request that inserts the raw JSON from the SF 311 API.

This JSON now needs to be parsed and formatted. 
The existing function sf311() can be modified to parse and loop through each JSON entry, each of which should have a service_request_id. It would be good to parse the JSON using an ordered list like:

<ul>
<li>service_request_id:13802151</li>
<li>key:value</li>
<li>key:value</li>
<li>key:value</li>
<li>key:value</li>
</ul>

Where key and value represent the different keys in the JSON.

vanilla JS should be fine for this! 

Loop through each entry, create one large HTML string, and set that var to populate the line:
document.getElementById("JSONresults").innerHTML = parsedJSON;

To test the file you can run index.html on any local HTML dev server. 

Comment below with any questions.

<a href="https://rysolv.com/issues/detail/35cb09c6-1e2e-4b84-9107-3a4991ec70c2"><img width="200px" src="https://rysolv.s3.us-east-2.amazonaws.com/FundingButton.png"></a>

**Comment by tpkahlon** [comment]
@masparasol: Please see solution function to achieve desired result.

Let me know if you have any adjustments you want to make. I skipped Rysolv's pull request because it might be easier for you to test the code on fly.

```
function sf311() {
    let data = null;
    let list = "<ul>";
    const xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function () {
        if (this.readyState == 4 && this.status == 200) {
        data = JSON.parse(this.responseText);
        data.forEach(function(item) {
            var keys = Object.keys(item);
            var values = Object.values(item);
            keys.forEach(function(key, index) {
            list += `<li>${keys[index]}: ${JSON.stringify(
                values[index]
            )}</li>`;
            });
        });
        list += "</ul>";
        document.getElementById("JSONresults").innerHTML = list;
        }
    };
    xhttp.open(
        "GET",
        "https://data.sfgov.org/resource/vw6y-z8j6.json?$where=requested_datetime between '2021-05-09T00:00:00.000' and '2021-05-09T23:59:59.000'",
        true
    );
    xhttp.send();
}
```

**Comment by masparasol** [comment]
Oh, thanks for this! I ended up going with a PR submitted through Rysolv, but I appreciate the code! 
I will be posting more issues either later today or next week so please keep an eye out. Thanks for the interest!
